### PR TITLE
Don't set history if a template doesn't exist

### LINKED ISSUE #934: Error when directly access /help
When browsing to https://www.righttoknow.org.au/help, a user gets an error message.

We receive the below error:
```ruby
An ActionView::MissingTemplate occurred in help#index:

Missing template help/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}. Searched in:
* "/srv/www/production/releases/20250826042603/lib/themes/righttoknow/lib/views"
* "/srv/www/production/releases/20250826042603/app/views"

lib/themes/righttoknow/lib/controller_patches.rb:17:in `set_history'
```

This *does not* affect people who click "help" on the website - only those who browse direclty to that page.

### PR DESCRIPTION
**Pull request by benrfairless**
Fixes #934

To test, browse to /help and confirm you are redirected to /help/about without an error.

### CODE REVIEW

File: lib/controller_patches.rb [hunk 1]
```diff
@@ -13,9 +13,13 @@ def house_rules; end
...
-      @history ||= HelpPageHistory.new(
-        lookup_context.find_template("#{controller_path}/#{action_name}")
-      )
+      # Only set history if a template exists for this action
+      begin
+        template = lookup_context.find_template("#{controller_path}/#{action_name}")
+        @history ||= HelpPageHistory.new(template)
+      rescue ActionView::MissingTemplate
+        # No template for this action, skip setting history
+      end
```
Comment (Br3nda) [inline lib/controller_patches.rb]: i think ruby let's you imply the `begin`
```suggestion
      # Only set history if a template exists for this action
      template = lookup_context.find_template("#{controller_path}/#{action_name}")
      @history ||= HelpPageHistory.new(template)
    rescue ActionView::MissingTemplate
      # No template for this action, skip setting history
```

**Review by Br3nda — APPROVED** [review]

**Comment by Br3nda** [comment]
This is on staging now
