### PR TITLE
Fix GitHub Changes links formatting in house rules page

### LINKED ISSUE #942: [Bug] Github Changes links are not formatted correctly
### Issue Type

Bug

### Description

To replicate:
1. Go to https://www.righttoknow.org.au/help/house_rules
2. Click "Github Repository" in the changes section at the bottom of the page:
Image

Expected Outcome:
User should be directed to https://github.com/openaustralia/righttoknow/commits/production/lib/views/help/house_rules.html.erb

Actual Outcome:
The URL displayed is: https://www.righttoknow.org.au/help/house_rules#%3CActionView::Template%20https://github.com/openaustralia/righttoknow/commits/production/lib/views/help/house_rules.html.erb%20locals=[]%3E

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by benrfairless**
Corrects the formatting of GitHub Changes links to direct users to the appropriate commits URL instead of an incorrectly formatted link. This change ensures that the links point to the correct GitHub repository path for the house rules page.

Fixes openaustralia/righttoknow#942

### CODE REVIEW

File: lib/help_page_history.rb [hunk 1]
```diff
@@ -7,7 +7,11 @@ def initialize(template)
   end
 
   def commits_url
-    template.inspect.gsub(/lib\/themes\/righttoknow/, GITHUB_BASE)
+    # Use the template identifier (full path) and replace the local path prefix with the GitHub base URL
+  path = template.identifier
+  filename = File.basename(path)
+  # Build the GitHub commits URL for this file
+  "#{GITHUB_BASE}/lib/views/help/#{filename}"
```
Comment (Br3nda) [inline lib/help_page_history.rb]: The indenting looks wrong here.

Comment (benrfairless) [reply lib/help_page_history.rb]: @Br3nda can you take another look? I hope that the changes I have made resolve the issue.

**Review by Br3nda — APPROVED** [review]
